adding hotfix branch pattern
equisoft-actions/nodejs-application-metadata pull request #6
Opened 2022-12-07 21:15 UTC by faroukhoumaidi

2022-12-07 21:17 UTC, toby-daigle approved these changes

2022-12-07 21:17 UTC, toby-daigle commented on action.yml
> +                  NPM_TAG="$VERSION"
@etremblay  tu penses qu'on est bon ici ?

2022-12-08 13:11 UTC, etremblay commented on action.yml
> +        git fetch --no-tags --prune --depth=1000 origin '+refs/heads/stable/*:refs/remotes/origin/stable/*'
on pourrait switcher les exemple sur release comme on utilise plus de branche stable nulle part

2022-12-08 21:43 UTC, etremblay approved these changes
Je suis mystifié que LATEST_VERSION était déjà là. Ça semblait même pas utilisé.

2022-12-08 21:43 UTC, etremblay commented on action.yml
> +        echo "### Aplication metadata" >> $GITHUB_STEP_SUMMARY
Je mettrais p-e une espace ici

2022-12-08 21:43 UTC, etremblay requested changes
tapeu

2022-12-08 21:45 UTC, etremblay commented on action.yml
> +                    NPM_TAG=snapshot
dans le cas d'un tag on met jamais snapshot (on garde ça pour les build sur master)

il faudrait mettre `latest` si "$NEXT_VERSION_MINOR" == "$LATEST_VERSION_MINOR"

2022-12-09 13:30 UTC, faroukhoumaidi commented on action.yml
> +        echo "### Aplication metadata" >> $GITHUB_STEP_SUMMARY
Genre une nouvelle ligne avant les metadatas?

2022-12-09 13:54 UTC, etremblay approved these changes
Bon boulot.

2022-12-09 13:55 UTC, merged